### ISSUE TITLE
Include slightly older LG TVs that have full remote control via RS232?

### ISSUE THREAD

**Issue by SlySven** [YooUp/RS232-Monitor-Commands#4]
I've a LG Plasma TV which has a (multiplex-able, one can set an ID number to send commands to a particular set - though I guess the receive data path is not usable) via a 9-pin D-type full RS232 interface on the back.  Preliminary investigations have enabled a Raspberry Pi (and a USB to serial port adapter) to bring it in/out of standby but I haven't sat down and done the local voice recognition system to literally tell the TV what to do yet...!

If I can find the PDF file (I think it was the manual for a similar, but not identical, model) would that be worth adding to this project?

**Comment by LucBerge** [comment]
I can take a look. What is the exact model of the TV ? Do you have a link to the LG website ?

**Comment by LucBerge** [comment]
Well, [LG screens are already supported](https://github.com/YooUp/RS232-Monitor-Commands/blob/master/database/monitors/lg.json). But maybe I can take a look at your TV. What is the exact model ? Do you have a link to the LG website ?

**Comment by LucBerge** [comment]
I've found this document : https://www.lg.com/us/support/products/documents/eng.pdf
P98 : The input select command looks ok

**Comment by SlySven** [comment]
Actually since I'm in the UK and my TV has PIP some of the codes may be different/extra - as mine is a 42PX5D variant I think the one I need is https://gscs-b2c.lge.com/downloadFile?fileId=KROWM000107881.pdf which I selected from https://www.lg.com/uk/support/manuals?superCateId= ...!

**Comment by LucBerge** [comment]
[Page 57 of your document](https://gscs-b2c.lge.com/downloadFile?fileId=KROWM000107881.pdf), the commands are the same as [the ones we use.](https://github.com/YooUp/RS232-Monitor-Commands/blob/master/database/monitors/lg.json). It should work. Are power ON/OFF the only commands you need ?
